# store stigg api keys to be used by apps and sidecars
apiVersion: v1
kind: Secret
metadata:
  name: stigg-api-keys
type: Opaque
data:
  SERVER_API_KEY: {{ .Values.serverApiKey | b64enc }}
  CLIENT_API_KEY: {{ .Values.stiggchart.clientApiKey | b64enc }}