{{- if .Values.persistentCache }}
# store redis credentials
apiVersion: v1
kind: Secret
metadata:
  name: stigg-redis-auth
type: Opaque
data:
  REDIS_USERNAME: {{ .Values.persistentCache.redis.username | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.persistentCache.redis.password | b64enc | quote }}
{{- end }}