apiVersion: v1
kind: ConfigMap
metadata:
  name: stigg-conf
  labels:
    app: stigg
    chart: {{ .Chart.Name }}
data:
  REDIS_ENVIRONMENT_PREFIX: {{ .Values.persistentCache.redis.environmentPrefix | quote }}
  REDIS_HOST: {{ .Values.persistentCache.redis.host | quote }}
  REDIS_PORT: {{ .Values.persistentCache.redis.port | quote }}
  REDIS_DB: {{ .Values.persistentCache.redis.db | quote }}
  REDIS_TLS: {{ .Values.persistentCache.redis.tls | quote }}
  AWS_REGION: {{ .Values.persistentCache.awsRegion | quote }}
  QUEUE_URL: {{ .Values.persistentCache.queueUrl | quote }}
